# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Verify No Changes
on:
  push:
    # Skip when it is a pull request from copybara as there might be changes in the proto schemas
    branches-ignore:
    - copybara
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Setup Node for gen/postgen scripts
      uses: actions/setup-node@v3
      with:
        node-version: '12'
    - name: Setup Go for proto2jsonschema script
      uses: actions/setup-go@v3
      with:
        go-version: '1.14'
    - name: Run the generators
      run: ./scripts/gen.sh
    - name: Ensure there is no diff
      run: git diff --exit-code .
